# Generated by Django 3.0.6 on 2020-06-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200606_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_flavour',
            field=models.CharField(default='', max_length=50),
        ),
    ]
